version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.0-node
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: lint
          command: bundle exec rubocop
      - run:
          name: test
          command: bundle exec rake
